version: "3.9" 
services:
  db:
    image: mongo
    container_name: dbmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: So1pass1S_2022
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - D:\Cursos\SOA1\Laboratorio\Practica1\mongoDB_Volume:/data/db
    networks:
      - clase4-net

  backend:
    image: dockerjaviercastillo/go-backend-201123924
    container_name: backend
    environment:
      DB_HOST: 192.168.1.2
    ports:
    - "3000:3000"
    restart: always
    depends_on:
    - db
    networks:
    - clase4-net

  frontend:
    image: dockerjaviercastillo/frontend-201123924 
    container_name: frontend
    ports:
    - "80:80"
    restart: always
    depends_on:
    - backend
    networks:
    - clase4-net
  
volumes:
  mongodata:

networks:
  clase4-net:
    name: "clase4-net"
    driver: bridge